# Eureka Server Port
server:
  port: 8761

# Eureka Server App Name
spring:
  application:
    name: discoveryservice

# Eureka Lib 가 포함되어 있는경우 기본적으로 Eureka Client 로 동작한다.
# 현재는 Eureka Server 이기 때문에 불필요하므로 비활성화 시킴 (기본은 true)
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false